# Generated by Django 4.0.1 on 2022-01-16 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=16, unique=True, verbose_name='Mobile phone'),
        ),
    ]
