# Generated by Django 4.0.1 on 2022-01-15 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproduct',
            old_name='product',
            new_name='cart_product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
